# Generated by Django 5.1.4 on 2025-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mensalidades_assinantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='categoria',
            field=models.CharField(default='sem categoria', max_length=100, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='endereco',
            field=models.CharField(default='null', max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
