# Generated by Django 5.1.4 on 2025-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='confirmada',
        ),
        migrations.AddField(
            model_name='empresas',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
    ]
