# Generated by Django 5.1.4 on 2025-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_assinatura_confirmada_empresas_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='cidade',
            field=models.CharField(default='goianinha', max_length=200, verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
